/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CheckboxVanilla {
        "checkboxValue": boolean;
        "itemId": string;
        "name": string;
    }
    interface CiccioForm {
    }
    interface SubmitBtn {
    }
    interface TextField {
        "fieldId": string;
        "fieldName": string;
        "fieldValue": string;
    }
}
declare global {
    interface HTMLCheckboxVanillaElement extends Components.CheckboxVanilla, HTMLStencilElement {
    }
    var HTMLCheckboxVanillaElement: {
        prototype: HTMLCheckboxVanillaElement;
        new (): HTMLCheckboxVanillaElement;
    };
    interface HTMLCiccioFormElement extends Components.CiccioForm, HTMLStencilElement {
    }
    var HTMLCiccioFormElement: {
        prototype: HTMLCiccioFormElement;
        new (): HTMLCiccioFormElement;
    };
    interface HTMLSubmitBtnElement extends Components.SubmitBtn, HTMLStencilElement {
    }
    var HTMLSubmitBtnElement: {
        prototype: HTMLSubmitBtnElement;
        new (): HTMLSubmitBtnElement;
    };
    interface HTMLTextFieldElement extends Components.TextField, HTMLStencilElement {
    }
    var HTMLTextFieldElement: {
        prototype: HTMLTextFieldElement;
        new (): HTMLTextFieldElement;
    };
    interface HTMLElementTagNameMap {
        "checkbox-vanilla": HTMLCheckboxVanillaElement;
        "ciccio-form": HTMLCiccioFormElement;
        "submit-btn": HTMLSubmitBtnElement;
        "text-field": HTMLTextFieldElement;
    }
}
declare namespace LocalJSX {
    interface CheckboxVanilla {
        "checkboxValue"?: boolean;
        "itemId"?: string;
        "name"?: string;
        "onChangeValue"?: (event: CustomEvent<any>) => void;
    }
    interface CiccioForm {
    }
    interface SubmitBtn {
        "onSubmitForm"?: (event: CustomEvent<any>) => void;
    }
    interface TextField {
        "fieldId"?: string;
        "fieldName"?: string;
        "fieldValue"?: string;
        "onChangeValue"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "checkbox-vanilla": CheckboxVanilla;
        "ciccio-form": CiccioForm;
        "submit-btn": SubmitBtn;
        "text-field": TextField;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "checkbox-vanilla": LocalJSX.CheckboxVanilla & JSXBase.HTMLAttributes<HTMLCheckboxVanillaElement>;
            "ciccio-form": LocalJSX.CiccioForm & JSXBase.HTMLAttributes<HTMLCiccioFormElement>;
            "submit-btn": LocalJSX.SubmitBtn & JSXBase.HTMLAttributes<HTMLSubmitBtnElement>;
            "text-field": LocalJSX.TextField & JSXBase.HTMLAttributes<HTMLTextFieldElement>;
        }
    }
}
